// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

namespace Pxp.Data
{

    /// 몬스터 타입
    public enum Enum_monsterType
    {
        None = 0,
        NORMAL = 1,
        BOSS = 2,
        BONUS = 3,
        THIEF = 4,
    }

    /// 아이템
    public enum Enum_ItemType
    {
        None = 0,
        Gem = 1,
        Gold = 2,
        Energy = 3,
        Ticket_NormalChest = 4,
    }

    /// 아이템 타입
    public enum Enum_TierType
    {
        None = 0,
        Normal = 1,
        Rare = 2,
        Epic = 3,
        Legend = 4,
    }
}
