// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

namespace Pxp.Data
{

    /// 몬스터 타입
    public enum Enum_monsterType
    {
        None = 0,
        NORMAL = 1,
        BOSS = 2,
        BONUS = 3,
        CAPTAIN = 4,
    }

    /// 아이템
    public enum Enum_ItemType
    {
        None = 0,
        Gem = 1,
        Gold = 2,
        Energy = 3,
        Ticket_NormalChest = 4,
        HeroIndex_1 = 5,
        HeroIndex_2 = 6,
        HeroIndex_3 = 7,
        HeroIndex_4 = 8,
        HeroIndex_5 = 9,
        HeroIndex_6 = 10,
        HeroIndex_7 = 11,
        HeroIndex_8 = 12,
        HeroIndex_9 = 13,
        HeroIndex_10 = 14,
        HeroIndex_11 = 15,
        HeroIndex_12 = 16,
        HeroIndex_13 = 17,
        HeroIndex_14 = 18,
        HeroIndex_15 = 19,
        HeroIndex_16 = 20,
        HeroIndex_17 = 21,
        HeroIndex_18 = 22,
        RelicIndex_1 = 23,
        RelicIndex_2 = 24,
        RelicIndex_3 = 25,
        RelicIndex_4 = 26,
        RelicIndex_5 = 27,
        RelicIndex_6 = 28,
        RelicIndex_7 = 29,
        RelicIndex_8 = 30,
        RelicIndex_9 = 31,
        RelicIndex_10 = 32,
        RelicIndex_11 = 33,
        RelicIndex_12 = 34,
        RelicIndex_13 = 35,
        RelicIndex_14 = 36,
        RelicIndex_15 = 37,
        RelicIndex_16 = 38,
        RelicIndex_17 = 39,
        RelicIndex_18 = 40,
        RelicIndex_19 = 41,
        RelicIndex_20 = 42,
        RelicIndex_21 = 43,
        RelicIndex_22 = 44,
        RelicIndex_23 = 45,
        RelicIndex_24 = 46,
        RelicIndex_25 = 47,
        Chest_Normal = 48,
        Chest_Shop_1 = 49,
        Chest_Shop_2 = 50,
        Chest_Relic = 51,
    }

    /// 등급 타입
    public enum Enum_TierType
    {
        None = 0,
        Normal = 1,
        Rare = 2,
        Epic = 3,
        Legend = 4,
    }

    /// 컨텐츠 타입
    public enum Enum_Content
    {
        None = 0,
    }

    /// 가챠 타입
    public enum Enum_gachaType
    {
        None = 0,
        Chest_Normal = 1,
        Chest_Shop_1 = 2,
        Chest_Shop_2 = 3,
        Chest_Relic = 4,
    }

    /// 상점 분류 타입
    public enum Enum_ShopCategory
    {
        None = 0,
        Package = 1,
        Chest = 2,
        Relic = 3,
        Gold = 4,
        Gem = 5,
        NormalChest = 6,
    }

    /// 구매 타입
    public enum Enum_PurchaseType
    {
        None = 0,
        Gem = 1,
        Gold = 2,
        IAP = 3,
        ADs = 4,
        Ticket_NormalChest = 5,
    }

    /// 미션 타입
    public enum Enum_QuestCondition
    {
        None = 0,
    }
}
