// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using System.Linq;
using System.Security.Cryptography;
using System.Text;
using CookApps.SpecData.Generator;

namespace PxP.Data
{
    [GeneratorSpecDataResource]
    public static partial class SpecDataResourceLoader
    {
        private static readonly byte[] _key = {41, 64, 84, 79, 117, 68, 50, 110, 41, 121, 68, 61, 110, 87, 118, 44};
    }
}
